import type { TransportOption } from '../types';

export const airports = {
  'London (All Airports)': [
    { code: 'LHR', name: 'Heathrow Airport' },
    { code: 'LGW', name: 'Gatwick Airport' },
    { code: 'STN', name: 'Stansted Airport' },
    { code: 'LTN', name: 'Luton Airport' },
    { code: 'LCY', name: 'London City Airport' },
  ],
  'Manchester': [
    { code: 'MAN', name: 'Manchester Airport' },
  ],
  'Birmingham': [
    { code: 'BHX', name: 'Birmingham Airport' },
  ],
  'Edinburgh': [
    { code: 'EDI', name: 'Edinburgh Airport' },
  ],
  'Glasgow': [
    { code: 'GLA', name: 'Glasgow Airport' },
  ],
  'Bristol': [
    { code: 'BRS', name: 'Bristol Airport' },
  ],
  'Newcastle': [
    { code: 'NCL', name: 'Newcastle Airport' },
  ],
  'Liverpool': [
    { code: 'LPL', name: 'Liverpool Airport' },
  ],
};

export const transportOptions = {
  LHR: [
    {
      mode: 'train' as const,
      duration: 15,
      price: 25,
      route: 'Heathrow Express',
      stops: 0,
      isEcoFriendly: true,
      isFastest: true,
      departureTime: '06:15',
      arrivalTime: '06:30',
    },
    {
      mode: 'subway' as const,
      duration: 45,
      price: 6,
      route: 'Piccadilly Line',
      stops: 8,
      isEcoFriendly: true,
      isCheapest: true,
      departureTime: '06:00',
      arrivalTime: '06:45',
    },
    {
      mode: 'bus' as const,
      duration: 60,
      price: 8,
      route: 'National Express',
      stops: 2,
      isEcoFriendly: false,
      departureTime: '06:30',
      arrivalTime: '07:30',
    },
    {
      mode: 'taxi' as const,
      duration: 35,
      price: 55,
      route: 'Direct via M4',
      stops: 0,
      isEcoFriendly: false,
      isBestOverall: true,
      departureTime: '06:00',
      arrivalTime: '06:35',
    },
  ],
  LGW: [
    {
      mode: 'train' as const,
      duration: 30,
      price: 20,
      route: 'Gatwick Express',
      stops: 0,
      isEcoFriendly: true,
      isFastest: true,
      departureTime: '06:15',
      arrivalTime: '06:45',
    },
    {
      mode: 'train' as const,
      duration: 45,
      price: 15,
      route: 'Southern Rail',
      stops: 3,
      isEcoFriendly: true,
      isCheapest: true,
      departureTime: '06:20',
      arrivalTime: '07:05',
    },
    {
      mode: 'bus' as const,
      duration: 75,
      price: 10,
      route: 'National Express',
      stops: 3,
      isEcoFriendly: false,
      departureTime: '06:45',
      arrivalTime: '08:00',
    },
    {
      mode: 'taxi' as const,
      duration: 50,
      price: 70,
      route: 'Direct via A23',
      stops: 0,
      isEcoFriendly: false,
      isBestOverall: true,
      departureTime: '06:00',
      arrivalTime: '06:50',
    },
  ],
  STN: [
    {
      mode: 'train' as const,
      duration: 36,
      price: 19,
      route: 'Stansted Express',
      stops: 1,
      isEcoFriendly: true,
      isFastest: true,
      departureTime: '06:25',
      arrivalTime: '07:01',
    },
    {
      mode: 'bus' as const,
      duration: 55,
      price: 12,
      route: 'National Express',
      stops: 2,
      isEcoFriendly: false,
      isCheapest: true,
      departureTime: '06:30',
      arrivalTime: '07:25',
    },
    {
      mode: 'taxi' as const,
      duration: 60,
      price: 85,
      route: 'Direct via M11',
      stops: 0,
      isEcoFriendly: false,
      isBestOverall: true,
      departureTime: '06:00',
      arrivalTime: '07:00',
    },
  ],
  LTN: [
    {
      mode: 'train' as const,
      duration: 45,
      price: 17,
      route: 'Luton Airport Parkway + Shuttle',
      stops: 2,
      isEcoFriendly: true,
      isCheapest: true,
      departureTime: '06:15',
      arrivalTime: '07:00',
    },
    {
      mode: 'bus' as const,
      duration: 65,
      price: 10,
      route: 'National Express',
      stops: 1,
      isEcoFriendly: false,
      departureTime: '06:45',
      arrivalTime: '07:50',
    },
    {
      mode: 'taxi' as const,
      duration: 40,
      price: 65,
      route: 'Direct via M1',
      stops: 0,
      isEcoFriendly: false,
      isFastest: true,
      isBestOverall: true,
      departureTime: '06:00',
      arrivalTime: '06:40',
    },
  ],
  LCY: [
    {
      mode: 'subway' as const,
      duration: 25,
      price: 5,
      route: 'DLR to Bank',
      stops: 6,
      isEcoFriendly: true,
      isFastest: true,
      isCheapest: true,
      isBestOverall: true,
      departureTime: '06:30',
      arrivalTime: '06:55',
    },
    {
      mode: 'taxi' as const,
      duration: 30,
      price: 35,
      route: 'Direct via A1020',
      stops: 0,
      isEcoFriendly: false,
      departureTime: '06:00',
      arrivalTime: '06:30',
    },
  ],
  MAN: [
    {
      mode: 'train' as const,
      duration: 20,
      price: 5,
      route: 'Airport Line to Piccadilly',
      stops: 4,
      isEcoFriendly: true,
      isFastest: true,
      isCheapest: true,
      isBestOverall: true,
      departureTime: '06:15',
      arrivalTime: '06:35',
    },
    {
      mode: 'bus' as const,
      duration: 35,
      price: 4,
      route: 'Stagecoach 43',
      stops: 6,
      isEcoFriendly: false,
      departureTime: '06:30',
      arrivalTime: '07:05',
    },
    {
      mode: 'taxi' as const,
      duration: 25,
      price: 30,
      route: 'Direct via A538',
      stops: 0,
      isEcoFriendly: false,
      departureTime: '06:00',
      arrivalTime: '06:25',
    },
  ],
};

export function generateMockTransportData(city: string): TransportOption[] {
  const cityAirports = airports[city as keyof typeof airports] || [{ code: 'XXX', name: 'City Airport' }];
  const options: TransportOption[] = [];

  cityAirports.forEach((airport) => {
    const airportOptions = transportOptions[airport.code as keyof typeof transportOptions] || [
      {
        mode: 'bus' as const,
        duration: 45,
        price: 12,
        route: 'City Express',
        stops: 2,
        isEcoFriendly: false,
        isCheapest: true,
        departureTime: '06:30',
        arrivalTime: '07:15',
      },
      {
        mode: 'taxi' as const,
        duration: 30,
        price: 40,
        route: 'Direct route',
        stops: 0,
        isEcoFriendly: false,
        isFastest: true,
        isBestOverall: true,
        departureTime: '06:00',
        arrivalTime: '06:30',
      },
    ];

    airportOptions.forEach((option, index) => {
      options.push({
        id: `${airport.code}-${option.mode}-${index}`,
        airportCode: airport.code,
        airportName: airport.name,
        mode: option.mode,
        duration: option.duration,
        price: option.price,
        destination: city.split(' ')[0] + ' City Centre',
        stops: option.stops,
        isEcoFriendly: option.isEcoFriendly || false,
        isFastest: option.isFastest || false,
        isCheapest: option.isCheapest || false,
        isBestOverall: option.isBestOverall || false,
        route: option.route,
        departureTime: option.departureTime,
        arrivalTime: option.arrivalTime,
      });
    });
  });

  return options;
}